'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {evaluate,GROUPS,RELIABILITY}=require('../scripts/evaluate-experience-pilot');
function passing(){return {schemaVersion:1,status:'collected',build:'fixture-only',sessionDate:'2026-09-05',highSeverityOpen:0,reliability:Object.fromEntries(RELIABILITY.map(key=>[key,{passed:true,evidence:'Synthetic evaluator fixture only'}])),groups:Object.fromEntries(GROUPS.map(group=>[group,Array.from({length:5},(_,i)=>({id:`${group}-${i}`,device:'desktop',order:i%2?'baseline_first':'redesign_first',ease:9,flow:9,tasks:Array.from({length:5},(_,j)=>({id:`task-${j}`,completedUnaided:true,nextActionCorrect:true,nextActorCorrect:true,nextActionSeconds:10,baselineNavigationAdminSeconds:100,redesignNavigationAdminSeconds:70}))}))]))};}
test('empty collection template cannot establish 9/10',()=>{assert.equal(evaluate(require('../reports/experience-pilot-template.json')).passed,false);});
test('acceptance requires every group, paired timings, and evidence for each reliability gate',()=>{const data=passing();assert.equal(evaluate(data).passed,true);data.groups.contributor[0].ease=8;assert.equal(evaluate(data).passed,false);data.groups.contributor[0].ease=9;delete data.groups.manager[0].tasks[0].baselineNavigationAdminSeconds;assert.equal(evaluate(data).passed,false);});
test('high severity defect or duplicated participants fail despite high averages',()=>{let data=passing();data.highSeverityOpen=1;assert.equal(evaluate(data).passed,false);data=passing();data.groups.sponsor[0].id=data.groups.contributor[0].id;assert.equal(evaluate(data).passed,false);data=passing();data.reliability.uploadRecovery.evidence='';assert.equal(evaluate(data).passed,false);});

test('next-action recognition includes the responsible person and retained-report integrity has its own gate',()=>{let data=passing();data.groups.coordinator[0].tasks.forEach(task=>task.nextActorCorrect=false);assert.equal(evaluate(data).passed,false);data=passing();delete data.groups.manager[0].tasks[0].nextActorCorrect;assert.equal(evaluate(data).passed,false);data=passing();delete data.reliability.retainedReportIntegrity;assert.equal(evaluate(data).passed,false);});
