#!/usr/bin/env node
// Content parity audit. Walks each per-framework content file and reports
// how many items carry each "audit-grade" field. The point isn't to grade
// the work; it's to surface the gap between frameworks so a consultant
// reading the README knows what to expect.
//
// Run: node scripts/content-parity.js
// Run with --markdown to regenerate data/CONTENT_PARITY.md.

const fs = require('fs');
const path = require('path');

// The six audit-grade fields that distinguish "catalog with descriptions"
// from "audit-grade content". Mirrors the shape that controls_assess.ejs
// expects on an ISO 27001 item.
const AUDIT_FIELDS = [
  'purpose',
  'what_good_looks_like',
  'common_pitfalls',
  'evidence_to_look_for',
  'maturity_ladder',
  'related_items'
];

function nonEmpty(v) {
  if (v == null) return false;
  if (typeof v === 'string') return v.trim().length > 0;
  if (Array.isArray(v)) return v.length > 0;
  if (typeof v === 'object') return Object.keys(v).length > 0;
  return true;
}

function flattenItems(mod) {
  // Returns a flat array of leaf items so the field-fill check sees one row
  // per actual content unit. Three shapes to handle:
  //   ISO 27001: array of items at top level
  //   ISO 42001: array of items at top level
  //   NIST CSF:  { FUNCTIONS: [{ categories: [{ subcategories: [...] }] }] }
  if (Array.isArray(mod)) return mod;
  if (mod && Array.isArray(mod.items)) return mod.items;
  if (mod && Array.isArray(mod.FUNCTIONS)) {
    const out = [];
    for (const fn of mod.FUNCTIONS) {
      for (const cat of fn.categories || []) {
        for (const sub of cat.subcategories || []) out.push(sub);
      }
    }
    return out;
  }
  if (mod && typeof mod === 'object') return Object.values(mod);
  return [];
}

function audit(name, file) {
  const mod = require(path.resolve(__dirname, '..', file));
  const items = flattenItems(mod);
  const total = items.length;
  const fill = {};
  for (const f of AUDIT_FIELDS) {
    fill[f] = items.filter(it => nonEmpty(it && it[f])).length;
  }
  return { name, file, total, fill };
}

function format(report, markdown) {
  const lines = [];
  const pad = (s, n) => String(s).padEnd(n);
  const bar = '|';
  if (markdown) {
    lines.push('# Content parity across frameworks');
    lines.push('');
    lines.push('Auto-generated by `scripts/content-parity.js`. Tracks how many');
    lines.push('per-item content blocks each framework provides on the six');
    lines.push('"audit-grade" fields that drive the gap-assessment UI:');
    lines.push('');
    for (const f of AUDIT_FIELDS) lines.push('- `' + f + '`');
    lines.push('');
    lines.push('| Framework | Items | ' + AUDIT_FIELDS.join(' | ') + ' |');
    lines.push('|' + '---|'.repeat(2 + AUDIT_FIELDS.length));
    for (const r of report) {
      const cells = AUDIT_FIELDS.map(f => {
        const c = r.fill[f];
        const pct = r.total ? Math.round(c / r.total * 100) : 0;
        return `${c}/${r.total} (${pct}%)`;
      });
      lines.push(`| ${r.name} | ${r.total} | ${cells.join(' | ')} |`);
    }
    lines.push('');
    lines.push('## What this means');
    lines.push('');
    lines.push('A row at 100% means every item in that framework carries that');
    lines.push('audit-grade field. A row at 0% means the framework is');
    lines.push('catalog-only on that dimension - the gap-assessment UI falls');
    lines.push('back to the catalog summary, which works but doesn\'t carry the');
    lines.push('same consultant insight per item.');
    lines.push('');
    lines.push('Pre-existing scaffolding for NIST CSF lives in');
    lines.push('`data/csf-analyst-content.js` (engagement-scoped explainers,');
    lines.push('analyst questions, evidence prompts, self-check prompts, learn');
    lines.push('docs). That fills the "workshop facilitation" gap but not the');
    lines.push('per-subcategory audit-grade gap above.');
  } else {
    for (const r of report) {
      lines.push(`--- ${r.name} (n=${r.total}) ---  [${r.file}]`);
      for (const f of AUDIT_FIELDS) {
        const c = r.fill[f];
        const pct = r.total ? Math.round(c / r.total * 100) : 0;
        lines.push(`  ${pad(f, 24)} ${c} / ${r.total}  (${pct}%)`);
      }
      lines.push('');
    }
  }
  return lines.join('\n');
}

function main() {
  const report = [
    audit('ISO 27001:2022', 'data/iso-content.js'),
    audit('ISO 42001:2023', 'data/iso42001-content.js'),
    audit('NIST CSF 2.0',   'data/nist-csf.js')
  ];
  const markdown = process.argv.includes('--markdown');
  const out = format(report, markdown);
  if (markdown) {
    const dest = path.resolve(__dirname, '..', 'data', 'CONTENT_PARITY.md');
    fs.writeFileSync(dest, out + '\n');
    console.log('wrote ' + path.relative(path.resolve(__dirname, '..'), dest));
  } else {
    console.log(out);
  }
}

main();
